### ISSUE TITLE
Implement `/unregister-webhook` endpoint

### ISSUE THREAD

**Issue by dsimog01** [dappnode/monitor-proxy#5]
There must be an endpoint called `/unregister-webhook` that receives the unregister requests from the grafana services of the monitors. This endpoint should not be exposed to the users, as it should only be called from inside the same docker network. The implementation of this endpoint implies it being removed from the monitor service, as stated in https://github.com/dappnode/monitor-service/issues/85

**Comment by pablomendezroyo** [comment]
Implemented
